export const CHECK_SESSION  = 'CHECK_SESSION';
export const USER_RECORD_SIGNIN = 'USER_RECORD_SIGNIN';
export const USER_RECORD_SIGNIN_SUCCESS = 'USER_RECORD_SIGNIN_SUCCESS';
export const USER_RECORD_SIGNIN_FAILURE = 'USER_RECORD_SIGNIN_FAILURE';

export const FETCH_DASHBOARD_HOME_LINK_BEAN     = 'FETCH_DASHBOARD_HOME_LINK_BEAN';
export const SUCCESS_DASHBOARD_HOME_LINK_BEAN   = 'SUCCESS_DASHBOARD_HOME_LINK_BEAN';
export const FAILURE_DASHBOARD_HOME_LINK_BEAN   = 'FAILURE_DASHBOARD_HOME_LINK_BEAN';